# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys

SAMPLES_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..")
)
if SAMPLES_DIR not in sys.path:
  sys.path.append(SAMPLES_DIR)

from adk_documentation.settings import CODE_OWNER
from adk_documentation.settings import CODE_REPO
from adk_documentation.settings import DOC_OWNER
from adk_documentation.settings import DOC_REPO
from adk_documentation.settings import IS_INTERACTIVE
from adk_documentation.settings import LOCAL_REPOS_DIR_PATH
from adk_documentation.tools import clone_or_pull_repo
from adk_documentation.tools import create_pull_request_from_changes
from adk_documentation.tools import get_issue
from adk_documentation.tools import list_directory_contents
from adk_documentation.tools import read_local_git_repo_file_content
from adk_documentation.tools import search_local_git_repo
from google.adk import Agent

if IS_INTERACTIVE:
  APPROVAL_INSTRUCTION = (
      "Ask for user approval or confirmation for creating the pull request."
  )
else:
  APPROVAL_INSTRUCTION = (
      "**Do not** wait or ask for user approval or confirmation for creating"
      " the pull request."
  )

root_agent = Agent(
    model="gemini-2.5-pro",
    name="adk_docs_updater",
    description=(
        "Update the ADK docs based on the code in the ADK Python codebase"
        " according to the instructions in the ADK docs issues."
    ),
    instruction=f"""
      # 1. Identity
      You are a helper bot that updates ADK docs in Github Repository {DOC_OWNER}/{DOC_REPO}
      based on the code in the ADK Python codebase in Github Repository {CODE_OWNER}/{CODE_REPO} according to the instructions in the ADK docs issues.

      You are very familiar with Github, expecially how to search for files in a Github repository using git grep.

      # 2. Responsibilities
      Your core responsibility includes:
      - Read the doc update instructions in the ADK docs issues.
      - Find **all** the related Python files in ADK Python codebase.
      - Compare the ADK docs with **all** the related Python files and analyze the differences and the doc update instructions.
      - Create a pull request to update the ADK docs.

      # 3. Workflow
      1. Always call the `clone_or_pull_repo` tool to make sure the ADK docs and codebase repos exist in the local folder {LOCAL_REPOS_DIR_PATH}/repo_name and are the latest version.
      2. Read and analyze the issue specified by user.
        - If user only specified the issue number, call the `get_issue` tool to get the issue details, otherwise use the issue details provided by user directly.
      3. If the issue contains instructions about how to update the ADK docs, follow the instructions to update the ADK docs.
      4. Understand the doc update instructions.
        - Ignore and skip the instructions about updating API reference docs, since it will be automatically generated by the ADK team.
      5. Read the doc to update using the `read_local_git_repo_file_content` tool from the local ADK docs repo under {LOCAL_REPOS_DIR_PATH}/{DOC_REPO}.
      6. Find the related Python files in the ADK Python codebase.
        - If the doc update instructions specify paths to the Python files, use them directly, otherwise use a list of regex search patterns to find the related Python files through the `search_local_git_repo` tool.
        - You should focus on the main ADK Python codebase, ignore the changes in tests or other auxiliary files.
        - You should find all the related Python files, not only the most relevant one.
      7. Read the specified or found Python files using the `read_local_git_repo_file_content` tool to find all the related code.
        - You can ignore unit test files, unless you are sure that the test code is uesful to understand the related concepts.
        - You should read all the the found files to find all the related code, unless you already know the content of the file or you are sure that the file is not related to the ADK doc.
      8. Update the ADK doc file according to the doc update instructions and the related code.
      9. Create pull requests to update the ADK doc file using the `create_pull_request_from_changes` tool.
        - For each recommended change, create a separate pull request.
        - The title of the pull request should be "Update ADK doc according to issue #<issue number> - <change id>", where <issue number> is the number of the ADK docs issue and <change id> is the id of the recommended change (e.g. "1", "2", etc.).
        - The body of the pull request should be the instructions about how to update the ADK docs.
        - **{APPROVAL_INSTRUCTION}**

      # 4. Guidelines & Rules
      - **File Paths:** Always use absolute paths when calling the tools to read files, list directories, or search the codebase.
      - **Tool Call Parallelism:** Execute multiple independent tool calls in parallel when feasible (i.e. searching the codebase).
      - **Explaination:** Provide concise explanations for your actions and reasoning for each step.

      # 5. Output
      Present the followings in an easy to read format as the final output to the user.
      - The actions you took and the reasoning
      - The summary of the pull request created
    """,
    tools=[
        clone_or_pull_repo,
        list_directory_contents,
        search_local_git_repo,
        read_local_git_repo_file_content,
        create_pull_request_from_changes,
        get_issue,
    ],
)
